(function() {var implementors = {};
implementors["i2c_linux"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"i2c_linux/struct.ReadFlags.html\" title=\"struct i2c_linux::ReadFlags\">ReadFlags</a>&gt; for <a class=\"struct\" href=\"http://arcnmx.github.io/i2c-rs/i2c/struct.ReadFlags.html\" title=\"struct i2c::ReadFlags\">I2cReadFlags</a>",synthetic:false,types:["i2c::ReadFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"http://arcnmx.github.io/i2c-rs/i2c/struct.ReadFlags.html\" title=\"struct i2c::ReadFlags\">I2cReadFlags</a>&gt; for <a class=\"struct\" href=\"i2c_linux/struct.ReadFlags.html\" title=\"struct i2c_linux::ReadFlags\">ReadFlags</a>",synthetic:false,types:["i2c_linux::ReadFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"i2c_linux/struct.WriteFlags.html\" title=\"struct i2c_linux::WriteFlags\">WriteFlags</a>&gt; for <a class=\"struct\" href=\"http://arcnmx.github.io/i2c-rs/i2c/struct.WriteFlags.html\" title=\"struct i2c::WriteFlags\">I2cWriteFlags</a>",synthetic:false,types:["i2c::WriteFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"http://arcnmx.github.io/i2c-rs/i2c/struct.WriteFlags.html\" title=\"struct i2c::WriteFlags\">I2cWriteFlags</a>&gt; for <a class=\"struct\" href=\"i2c_linux/struct.WriteFlags.html\" title=\"struct i2c_linux::WriteFlags\">WriteFlags</a>",synthetic:false,types:["i2c_linux::WriteFlags"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
